---
name: Security

on: pull_request

jobs:
  
  # Thanks https://black.readthedocs.io/en/stable/integrations/github_actions.html
  bandit:
    name: Bandit
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      - name: bandit
        uses: mdegis/bandit-action@v1.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          level: medium
          confidence: medium
